//! Round-trip tests for float/half sample_format and varied bit depths.
//!
//! Unlike `integration_test.rs` (which depends on an external image and
//! "skips" when it does not exist), these tests generate the input image in
//! memory via the `image` crate and verify the fidelity of the decoded pixels.

use cafe::{decode, encode, EncodeOptions};

const W: u32 = 16;
const H: u32 = 16;

fn make_test_image() -> image::RgbaImage {
    let mut img = image::RgbaImage::new(W, H);
    for (x, y, px) in img.enumerate_pixels_mut() {
        *px = image::Rgba([
            ((x * 17) % 256) as u8,
            ((y * 17) % 256) as u8,
            ((x * y + 1) % 256) as u8,
            ((x + y * 7) % 256) as u8,
        ]);
    }
    img
}

/// Expected gray value (same Y formula as the encoder).
fn gray_value(r: u8, g: u8, b: u8) -> u8 {
    ((299 * u32::from(r) + 587 * u32::from(g) + 114 * u32::from(b)) / 1000).min(255) as u8
}

/// Builds the expected RGBA after a round-trip that reduces the color type.
fn expected_for(color_type: u8) -> Vec<u8> {
    let src = make_test_image().into_raw();
    let mut expected = src.clone();
    for px in expected.chunks_exact_mut(4) {
        let (r, g, b) = (px[0], px[1], px[2]);
        match color_type {
            0 => {
                // GRAY: single channel replicated; alpha discarded
                let y = gray_value(r, g, b);
                px[0] = y;
                px[1] = y;
                px[2] = y;
                px[3] = 255;
            }
            2 => {
                // RGB: alpha discarded
                px[3] = 255;
            }
            4 => {
                // GRAY_ALPHA: gray replicated, alpha preserved
                let y = gray_value(r, g, b);
                px[0] = y;
                px[1] = y;
                px[2] = y;
            }
            _ => {}
        }
    }
    expected
}

/// Runs encode+decode of a generated image and returns the decoded RGBA pixels
/// (read back from the PNG generated by the decoder).
fn roundtrip(opts: &EncodeOptions, label: &str) -> Vec<u8> {
    let dir = std::env::temp_dir().join("cafe_roundtrip");
    std::fs::create_dir_all(&dir).unwrap();

    let input_path = dir.join(format!("{label}_in.png"));
    let cafe_path = dir.join(format!("{label}.cafe"));
    let out_path = dir.join(format!("{label}_out.png"));

    make_test_image().save(&input_path).unwrap();

    encode(
        input_path.to_str().unwrap(),
        cafe_path.to_str().unwrap(),
        opts,
    )
    .expect("encode failed");
    decode(cafe_path.to_str().unwrap(), out_path.to_str().unwrap()).expect("decode failed");

    let decoded = image::open(&out_path)
        .expect("failed to read decoded PNG")
        .to_rgba8();
    decoded.into_raw()
}

/// Compares RGBA pixels allowing a tolerance of ±2 per channel (float/half are
/// lossy in floating-point conversion).
fn assert_pixels_close(actual: &[u8], expected: &[u8], tolerance: u8) {
    assert_eq!(actual.len(), expected.len(), "pixel size differs");
    for (a, e) in actual.iter().zip(expected.iter()) {
        let diff = (*a).abs_diff(*e);
        assert!(
            diff <= tolerance,
            "pixel diverged: got {a}, expected {e} (tol {tolerance})"
        );
    }
}

#[test]
fn roundtrip_float_rgba() {
    let opts = EncodeOptions {
        sample_format: Some(1), // SAMPLE_FORMAT_FLOAT
        ..EncodeOptions::default()
    };
    let pixels = roundtrip(&opts, "float_rgba");
    let expected = expected_for(6);
    assert_pixels_close(&pixels, &expected, 2);
}

#[test]
fn roundtrip_half_rgba() {
    let opts = EncodeOptions {
        sample_format: Some(2), // SAMPLE_FORMAT_HALF
        ..EncodeOptions::default()
    };
    let pixels = roundtrip(&opts, "half_rgba");
    let expected = expected_for(6);
    assert_pixels_close(&pixels, &expected, 2);
}

#[test]
fn roundtrip_float_rgb() {
    let opts = EncodeOptions {
        sample_format: Some(1),
        target_color_type: 2, // COLOR_TYPE_RGB
        ..EncodeOptions::default()
    };
    let pixels = roundtrip(&opts, "float_rgb");
    let expected = expected_for(2);
    assert_pixels_close(&pixels, &expected, 2);
}

#[test]
fn roundtrip_half_gray_alpha() {
    let opts = EncodeOptions {
        sample_format: Some(2),
        target_color_type: 4, // COLOR_TYPE_GRAY_ALPHA
        ..EncodeOptions::default()
    };
    let pixels = roundtrip(&opts, "half_gray_alpha");
    let expected = expected_for(4);
    assert_pixels_close(&pixels, &expected, 3);
}

#[test]
fn roundtrip_float_gray() {
    let opts = EncodeOptions {
        sample_format: Some(1),
        target_color_type: 0, // COLOR_TYPE_GRAY
        ..EncodeOptions::default()
    };
    let pixels = roundtrip(&opts, "float_gray");
    let expected = expected_for(0);
    assert_pixels_close(&pixels, &expected, 2);
}

#[test]
fn roundtrip_uint_16bit_rgba() {
    let opts = EncodeOptions {
        target_bit_depth: Some(16),
        target_color_type: 6, // COLOR_TYPE_RGBA
        ..EncodeOptions::default()
    };
    let pixels = roundtrip(&opts, "uint16_rgba");
    let expected = expected_for(6);
    assert_pixels_close(&pixels, &expected, 1);
}

// ---------------------------------------------------------------------------
// Byte-shuffle (Filter Method = 1): end-to-end round-trip that exercises the
// byte reordering on encode and undoes it on decode.
// ---------------------------------------------------------------------------

#[test]
fn roundtrip_byte_shuffle_rgba_8bit() {
    // bpp=4 (RGBA 8-bit): byte-shuffle is lossless → exact round-trip
    let opts = EncodeOptions {
        use_byte_shuffle: true,
        target_color_type: 6, // COLOR_TYPE_RGBA
        ..EncodeOptions::default()
    };
    let pixels = roundtrip(&opts, "byte_shuffle_rgba8");
    let expected = expected_for(6);
    assert_pixels_close(&pixels, &expected, 0);
}

#[test]
fn roundtrip_byte_shuffle_rgba_16bit() {
    // bpp=8 (RGBA 16-bit): byte-shuffle over 2-byte samples
    let opts = EncodeOptions {
        use_byte_shuffle: true,
        target_bit_depth: Some(16),
        target_color_type: 6, // COLOR_TYPE_RGBA
        ..EncodeOptions::default()
    };
    let pixels = roundtrip(&opts, "byte_shuffle_rgba16");
    let expected = expected_for(6);
    assert_pixels_close(&pixels, &expected, 1);
}

#[test]
fn roundtrip_byte_shuffle_float_rgba() {
    // bpp=16 (RGBA float): byte-shuffle improves float data compression
    let opts = EncodeOptions {
        use_byte_shuffle: true,
        sample_format: Some(1), // SAMPLE_FORMAT_FLOAT
        target_color_type: 6,   // COLOR_TYPE_RGBA
        ..EncodeOptions::default()
    };
    let pixels = roundtrip(&opts, "byte_shuffle_float_rgba");
    let expected = expected_for(6);
    assert_pixels_close(&pixels, &expected, 2);
}

// ---------------------------------------------------------------------------
// Tiling 2D (iDIM): end-to-end round-trip that exercises partition into tiles,
// one IDAT per tile in scan_order order and reassembly in the decoder.
// ---------------------------------------------------------------------------

/// Generates an RGBA image of arbitrary dims with a deterministic pattern.
fn make_image(w: u32, h: u32) -> image::RgbaImage {
    let mut img = image::RgbaImage::new(w, h);
    for (x, y, px) in img.enumerate_pixels_mut() {
        *px = image::Rgba([
            ((x * 7 + y * 3) % 256) as u8,
            ((x * 13 + y % 256) % 256) as u8,
            ((x + y * 29) % 256) as u8,
            ((x * 3 + y * 5) % 256) as u8,
        ]);
    }
    img
}

/// Round-trip of an image with arbitrary dims; returns decoded RGBA pixels.
fn roundtrip_size(opts: &EncodeOptions, w: u32, h: u32, label: &str) -> Vec<u8> {
    roundtrip_image(make_image(w, h), opts, label)
}

fn roundtrip_image(img: image::RgbaImage, opts: &EncodeOptions, label: &str) -> Vec<u8> {
    let dir = std::env::temp_dir().join("cafe_roundtrip");
    std::fs::create_dir_all(&dir).unwrap();

    let input_path = dir.join(format!("{label}_in.png"));
    let cafe_path = dir.join(format!("{label}.cafe"));
    let out_path = dir.join(format!("{label}_out.png"));

    img.save(&input_path).unwrap();
    encode(
        input_path.to_str().unwrap(),
        cafe_path.to_str().unwrap(),
        opts,
    )
    .expect("encode failed");
    decode(cafe_path.to_str().unwrap(), out_path.to_str().unwrap()).expect("decode failed");

    image::open(&out_path)
        .expect("failed to read decoded PNG")
        .to_rgba8()
        .into_raw()
}

fn idim_tiling(tile_w: u16, tile_h: u16, scan_order: u8) -> cafe::iDim {
    cafe::iDim::new(tile_w, tile_h, 33, 23, scan_order)
}

#[test]
fn roundtrip_tiling_rowmajor() {
    // Image 33x23, tile 8x8 → 5x4 = 20 tiles (partial edges).
    let opts = EncodeOptions {
        idim: Some(idim_tiling(8, 8, 0)),
        ..EncodeOptions::default()
    };
    let pixels = roundtrip_size(&opts, 33, 23, "tiling_rowmajor");
    assert_pixels_close(&pixels, &make_image(33, 23).into_raw(), 0);
}

#[test]
fn roundtrip_tiling_zorder() {
    let opts = EncodeOptions {
        idim: Some(idim_tiling(8, 8, 1)),
        ..EncodeOptions::default()
    };
    let pixels = roundtrip_size(&opts, 33, 23, "tiling_zorder");
    assert_pixels_close(&pixels, &make_image(33, 23).into_raw(), 0);
}

#[test]
fn roundtrip_tiling_no_filter() {
    let opts = EncodeOptions {
        idim: Some(idim_tiling(16, 8, 0)),
        use_filter: false,
        ..EncodeOptions::default()
    };
    let pixels = roundtrip_size(&opts, 33, 23, "tiling_no_filter");
    assert_pixels_close(&pixels, &make_image(33, 23).into_raw(), 0);
}

#[test]
fn roundtrip_tiling_non_power_two() {
    // Tile 25x11 (non-divisor) to exercise partial edges in both directions.
    let opts = EncodeOptions {
        idim: Some(idim_tiling(25, 11, 0)),
        ..EncodeOptions::default()
    };
    let pixels = roundtrip_size(&opts, 33, 23, "tiling_non_power_two");
    assert_pixels_close(&pixels, &make_image(33, 23).into_raw(), 0);
}

#[test]
fn roundtrip_byte_shuffle_tiling() {
    // Byte-shuffle + iDIM (tiling 2D): exercises per-tile shuffle decode
    // with tile dimensions (not the whole image).
    let opts = EncodeOptions {
        use_byte_shuffle: true,
        idim: Some(idim_tiling(8, 8, 0)),
        ..EncodeOptions::default()
    };
    let pixels = roundtrip_size(&opts, 33, 23, "byte_shuffle_tiling");
    assert_pixels_close(&pixels, &make_image(33, 23).into_raw(), 0);
}

/// Encodes a single file and returns the Result (without unwrap) for tests of
/// rejection of invalid combinations.
fn encode_result(opts: &EncodeOptions, label: &str) -> Result<(), cafe::error::CafeError> {
    let dir = std::env::temp_dir().join("cafe_roundtrip");
    std::fs::create_dir_all(&dir).unwrap();
    let input_path = dir.join(format!("{label}_in.png"));
    let cafe_path = dir.join(format!("{label}.cafe"));
    make_test_image().save(&input_path).unwrap();
    encode(
        input_path.to_str().unwrap(),
        cafe_path.to_str().unwrap(),
        opts,
    )
}

#[test]
fn byte_shuffle_rejects_bpp3_rgb() {
    // RGB 8-bit has bpp=3, outside {2,4,8,16} → byte-shuffle must be rejected
    // at encode time (CWE-20: never produce a file with an invalid configuration).
    let opts = EncodeOptions {
        use_byte_shuffle: true,
        target_color_type: 2, // COLOR_TYPE_RGB (3 bytes/pixel)
        ..EncodeOptions::default()
    };
    let res = encode_result(&opts, "bs_reject_rgb");
    assert!(res.is_err(), "byte-shuffle with bpp=3 should be rejected");
}

#[test]
fn byte_shuffle_rejects_interlace() {
    // Byte-shuffle is incompatible with interlace → must be rejected at encode.
    let opts = EncodeOptions {
        use_byte_shuffle: true,
        interlace_method: 1, // Adam7
        ..EncodeOptions::default()
    };
    let res = encode_result(&opts, "bs_reject_interlace");
    assert!(res.is_err(), "byte-shuffle + interlace should be rejected");
}

// ---------------------------------------------------------------------------
// Structured metadata: jSON, eXIF, iCCP, xMPd and zDIC (ancillary chunks).
// ---------------------------------------------------------------------------

#[test]
fn roundtrip_metadata_chunks() {
    let dir = std::env::temp_dir().join("cafe_roundtrip");
    std::fs::create_dir_all(&dir).unwrap();

    let input_path = dir.join("meta_in.png");
    let cafe_path = dir.join("meta.cafe");
    let out_path = dir.join("meta_out.png");
    make_test_image().save(&input_path).unwrap();

    let mut json = std::collections::HashMap::new();
    json.insert(
        "camera".to_string(),
        serde_json::json!({ "model": "TestCam", "iso": 100 }),
    );
    json.insert(
        "author".to_string(),
        serde_json::json!({ "name": "CAFE Tests" }),
    );
    let exif = vec![0x45u8, 0x58, 0x49, 0x46, 0x00, 0x2A, 0xFF];
    let icc = vec![0xABu8; 96];
    let xmp = "<x:xmpmeta xmlns:x=\"adobe:ns:meta/\">test</x:xmpmeta>".to_string();
    let dict = vec![0x5Au8; 256];

    let opts = EncodeOptions {
        json_metadata: json.clone(),
        exif: Some(exif.clone()),
        icc_profile: Some(icc.clone()),
        xmp_metadata: Some(xmp.clone()),
        zstd_dictionary: Some(dict.clone()),
        ..EncodeOptions::default()
    };

    encode(
        input_path.to_str().unwrap(),
        cafe_path.to_str().unwrap(),
        &opts,
    )
    .expect("encode failed");

    let result =
        decode(cafe_path.to_str().unwrap(), out_path.to_str().unwrap()).expect("decode failed");

    assert_eq!(result.json_metadata, json, "jSON metadata diverged");
    assert_eq!(
        result.exif.as_deref(),
        Some(exif.as_slice()),
        "eXIF diverged"
    );
    assert_eq!(
        result.icc_profile.as_deref(),
        Some(icc.as_slice()),
        "iCCP diverged"
    );
    assert_eq!(
        result.xmp_metadata.as_deref(),
        Some(xmp.as_str()),
        "xMPd diverged"
    );
    assert_eq!(
        result.zstd_dictionary.as_deref(),
        Some(dict.as_slice()),
        "zDIC diverged"
    );
}

#[test]
fn roundtrip_metadata_empty_json() {
    // Empty jSON in the encoder → decoder must deliver an empty map (no panics).
    let dir = std::env::temp_dir().join("cafe_roundtrip");
    std::fs::create_dir_all(&dir).unwrap();

    let input_path = dir.join("meta_empty_in.png");
    let cafe_path = dir.join("meta_empty.cafe");
    let out_path = dir.join("meta_empty_out.png");
    make_test_image().save(&input_path).unwrap();

    let opts = EncodeOptions {
        ..EncodeOptions::default()
    };
    encode(
        input_path.to_str().unwrap(),
        cafe_path.to_str().unwrap(),
        &opts,
    )
    .expect("encode failed");
    let result =
        decode(cafe_path.to_str().unwrap(), out_path.to_str().unwrap()).expect("decode failed");
    assert!(result.json_metadata.is_empty());
    assert!(result.exif.is_none());
    assert!(result.icc_profile.is_none());
    assert!(result.xmp_metadata.is_none());
    assert!(result.zstd_dictionary.is_none());
}
