//! Golden-file tests for `cafe-format` (Phase 4, see `AGENTS.md`).
//!
//! `cafe-format` only knows chunk framing + `IHDR` — it has no predictor
//! reversal or pixel semantics (that's `cafe-codec`, Phase 5+). So these
//! goldens exercise exactly what this crate is responsible for: signature
//! validation, chunk framing/CRC32, and `IHDR` parsing/validation. `IDAT`
//! payloads here are opaque bytes from this crate's point of view (still
//! shaped like real predictor-prefixed rows, so they'll be meaningful
//! fixtures once `cafe-codec` exists) — this crate never interprets them.
//!
//! Fixtures live in `golden/` (valid) and `golden/malformed/` (adversarial)
//! at the workspace root, generated by [`generate_golden_fixtures`] below.
//! That generator is `#[ignore]`d (not run on every `cargo test`) since the
//! fixtures are committed to the repo — run it manually with
//! `cargo test -p cafe-format --test golden_files -- --ignored` after a
//! deliberate, reviewed change to the fixture set itself.

use cafe_format::chunk::{read_chunk, write_chunk};
use cafe_format::constants::{
    COLOR_TYPE_GRAY, COLOR_TYPE_RGBA, COMPRESSION_METHOD_ZSTD_BIT, SAMPLE_FORMAT_UINT, SIGNATURE,
};
use cafe_format::error::CafeError;
use cafe_format::ihdr::{read_ihdr, Ihdr};
use cafe_format::validate_signature;
use std::path::{Path, PathBuf};

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("golden")
}

fn read_golden(name: &str) -> Vec<u8> {
    let path = golden_dir().join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("failed to read golden {path:?}: {e}"))
}

fn read_malformed(name: &str) -> Vec<u8> {
    let path = golden_dir().join("malformed").join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("failed to read golden {path:?}: {e}"))
}

/// Parses everything this crate knows how to parse: signature, `IHDR`, then
/// every following chunk via raw `read_chunk` (framing/CRC only — no
/// pixel/predictor interpretation). Returns the parsed `IHDR` and the list
/// of subsequent chunk types encountered, in order.
fn parse_minimal(buf: &[u8]) -> cafe_format::Result<(Ihdr, Vec<String>)> {
    let mut offset = validate_signature(buf)?;
    let (ihdr, next) = read_ihdr(buf, offset)?;
    offset = next;

    let mut types = Vec::new();
    while offset < buf.len() {
        let chunk = read_chunk(buf, offset)?;
        types.push(String::from_utf8_lossy(&chunk.chunk_type).to_string());
        offset = chunk.next_offset;
    }
    Ok((ihdr, types))
}

// --- Valid fixtures ---

#[test]
fn test_minimal_1x1_gray_parses_and_validates() {
    let buf = read_golden("minimal_1x1_gray.cafe");
    let (ihdr, types) = parse_minimal(&buf).expect("golden file should parse cleanly");
    assert_eq!(ihdr.width, 1);
    assert_eq!(ihdr.height, 1);
    assert_eq!(ihdr.bit_depth, 8);
    assert_eq!(ihdr.color_type, COLOR_TYPE_GRAY);
    assert_eq!(types, vec!["IDAT", "IEND"]);
}

#[test]
fn test_minimal_2x2_rgba_parses_and_validates() {
    let buf = read_golden("minimal_2x2_rgba.cafe");
    let (ihdr, types) = parse_minimal(&buf).expect("golden file should parse cleanly");
    assert_eq!(ihdr.width, 2);
    assert_eq!(ihdr.height, 2);
    assert_eq!(ihdr.bit_depth, 8);
    assert_eq!(ihdr.color_type, COLOR_TYPE_RGBA);
    assert_eq!(types, vec!["IDAT", "IEND"]);
}

// --- Malformed fixtures ---

#[test]
fn test_malformed_bad_signature_is_rejected() {
    let buf = read_malformed("bad_signature.cafe");
    assert!(matches!(
        parse_minimal(&buf),
        Err(CafeError::InvalidSignature)
    ));
}

#[test]
fn test_malformed_truncated_header_is_rejected() {
    let buf = read_malformed("truncated_header.cafe");
    assert!(matches!(
        parse_minimal(&buf),
        Err(CafeError::TruncatedFile(_))
    ));
}

#[test]
fn test_malformed_crc_mismatch_is_rejected() {
    let buf = read_malformed("crc_mismatch.cafe");
    assert!(matches!(
        parse_minimal(&buf),
        Err(CafeError::CrcMismatch { .. })
    ));
}

#[test]
fn test_malformed_invalid_ihdr_zero_width_is_rejected() {
    let buf = read_malformed("invalid_ihdr_zero_width.cafe");
    assert!(matches!(
        parse_minimal(&buf),
        Err(CafeError::InvalidIhdr(_))
    ));
}

#[test]
fn test_malformed_forged_length_is_rejected() {
    let buf = read_malformed("forged_length.cafe");
    assert!(matches!(
        parse_minimal(&buf),
        Err(CafeError::TruncatedFile(_))
    ));
}

#[test]
fn test_malformed_wrong_first_chunk_type_is_rejected() {
    let buf = read_malformed("wrong_first_chunk.cafe");
    assert!(matches!(
        parse_minimal(&buf),
        Err(CafeError::UnexpectedChunkType { .. })
    ));
}

// --- Fixture generator (not run by default - see module doc comment) ---

#[test]
#[ignore = "regenerates golden fixtures; run manually after a deliberate, reviewed change"]
fn generate_golden_fixtures() {
    let dir = golden_dir();
    let malformed_dir = dir.join("malformed");
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::create_dir_all(&malformed_dir).unwrap();

    // --- minimal_1x1_gray.cafe: smallest possible valid file ---
    let gray_ihdr = Ihdr {
        width: 1,
        height: 1,
        bit_depth: 8,
        sample_format: SAMPLE_FORMAT_UINT,
        color_type: COLOR_TYPE_GRAY,
        compression_method: 0, // no chunk in this file uses ZSTD
    };
    let mut buf = SIGNATURE.to_vec();
    buf.extend(gray_ihdr.to_chunk_bytes());
    // One row: predictor=0 (None) + one gray sample.
    buf.extend(write_chunk(b"IDAT", 0x00, &[0x00, 0x7F]));
    buf.extend(write_chunk(b"IEND", 0x00, b""));
    std::fs::write(dir.join("minimal_1x1_gray.cafe"), &buf).unwrap();

    // --- minimal_2x2_rgba.cafe: exercises multi-row, multi-channel, and
    // the ZSTD capability bit (still raw Flag - 2x2 RGBA is far too small
    // for compression to ever win the fallback race, spec section 3.2). ---
    let rgba_ihdr = Ihdr {
        width: 2,
        height: 2,
        bit_depth: 8,
        sample_format: SAMPLE_FORMAT_UINT,
        color_type: COLOR_TYPE_RGBA,
        compression_method: COMPRESSION_METHOD_ZSTD_BIT,
    };
    let mut buf = SIGNATURE.to_vec();
    buf.extend(rgba_ihdr.to_chunk_bytes());
    // Two rows, 2 pixels * 4 channels = 8 bytes/row, predictor=0 (None) each.
    let mut idat_payload = Vec::new();
    idat_payload.push(0x00); // row 0 predictor: None
    idat_payload.extend_from_slice(&[0x10, 0x20, 0x30, 0xFF, 0x11, 0x21, 0x31, 0xFF]);
    idat_payload.push(0x00); // row 1 predictor: None
    idat_payload.extend_from_slice(&[0x12, 0x22, 0x32, 0xFF, 0x13, 0x23, 0x33, 0xFF]);
    buf.extend(write_chunk(b"IDAT", 0x00, &idat_payload));
    buf.extend(write_chunk(b"IEND", 0x00, b""));
    std::fs::write(dir.join("minimal_2x2_rgba.cafe"), &buf).unwrap();

    // --- malformed/bad_signature.cafe: wrong magic bytes ---
    let mut buf = vec![0u8; 9];
    buf[0] = 0x89; // keep the high-bit-detection byte, corrupt the rest
    std::fs::write(malformed_dir.join("bad_signature.cafe"), &buf).unwrap();

    // --- malformed/truncated_header.cafe: EOF partway through IHDR's
    // chunk header (Length+Type+Flag is 9 bytes; only 5 are present) ---
    let mut buf = SIGNATURE.to_vec();
    let full_ihdr = gray_ihdr.to_chunk_bytes();
    buf.extend_from_slice(&full_ihdr[..5]);
    std::fs::write(malformed_dir.join("truncated_header.cafe"), &buf).unwrap();

    // --- malformed/crc_mismatch.cafe: valid framing, corrupted CRC32 ---
    let mut buf = SIGNATURE.to_vec();
    let mut ihdr_bytes = gray_ihdr.to_chunk_bytes();
    let last = ihdr_bytes.len() - 1;
    ihdr_bytes[last] ^= 0xFF; // flip a bit in the CRC32 footer
    buf.extend(ihdr_bytes);
    std::fs::write(malformed_dir.join("crc_mismatch.cafe"), &buf).unwrap();

    // --- malformed/invalid_ihdr_zero_width.cafe: framing/CRC valid, but
    // Width=0 violates spec section 4.1's "> 0" constraint ---
    let mut zero_width_ihdr = gray_ihdr;
    zero_width_ihdr.width = 0;
    let mut buf = SIGNATURE.to_vec();
    buf.extend(zero_width_ihdr.to_chunk_bytes());
    std::fs::write(malformed_dir.join("invalid_ihdr_zero_width.cafe"), &buf).unwrap();

    // --- malformed/forged_length.cafe: IHDR's Length field claims more
    // bytes than actually follow it (CWE-409-adjacent framing check,
    // spec section 8.1) ---
    let mut buf = SIGNATURE.to_vec();
    buf.extend_from_slice(&(1000u32).to_be_bytes()); // forged Length
    buf.extend_from_slice(b"IHDR");
    buf.push(0x00);
    buf.extend_from_slice(b"not actually 1000 bytes of data");
    std::fs::write(malformed_dir.join("forged_length.cafe"), &buf).unwrap();

    // --- malformed/wrong_first_chunk.cafe: first chunk after the
    // signature is not IHDR (spec section 5: IHDR must be first) ---
    let mut buf = SIGNATURE.to_vec();
    buf.extend(write_chunk(b"IDAT", 0x00, b"pixels before a header"));
    std::fs::write(malformed_dir.join("wrong_first_chunk.cafe"), &buf).unwrap();
}
