//! Streaming encode example with CAFE
//!
//! Demonstrates the `Encoder<W: Write>` / `Encoder<W: Write + Seek>` API
//! (v1.6+): encodes an image one row-strip tile at a time instead of
//! buffering the whole encoded output in memory the way `encode()` does
//! internally before writing it out.
//!
//! This is useful when pixels become available incrementally (e.g.
//! generated by a renderer, decoded from another format tile-by-tile via
//! `Decoder<R>`, or streamed in over a network) and you want to start
//! writing compressed `IDAT` chunks as soon as each tile is ready, rather
//! than waiting for the entire image to be assembled in memory first.
//!
//! For demonstration purposes only, this example still loads the whole
//! source PNG into memory via the `image` crate (since that's the simplest
//! way to obtain RGBA pixels from a file) and then slices it into tiles —
//! a real streaming producer would hand `Encoder::add_tile()` each tile as
//! it becomes available instead.
//!
//! # Limitations
//! `Encoder<W>` only supports row-strip tiling (no `iDIM` 2D tiling, no
//! Adam7/even-odd interlacing) and direct color types (no indexed palette —
//! use `encode_indexed()` for that, since palette quantization requires
//! seeing the whole image upfront). See `EncoderOptions`'s doc comment for
//! the full list of what's out of scope for this streaming API.
//!
//! Usage:
//! ```bash
//! cargo run --example streaming_encode -- input.png output.cafe [tile_rows]
//! ```

use cafe::{constants, Encoder, EncoderOptions};
use std::env;
use std::fs::File;
use std::io::BufWriter;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = env::args().collect();

    if args.len() < 3 {
        eprintln!("Usage: {} <input.png> <output.cafe> [tile_rows]", args[0]);
        std::process::exit(1);
    }

    let input_path = &args[1];
    let output_path = &args[2];
    let tile_rows: u32 = args
        .get(3)
        .and_then(|s| s.parse().ok())
        .unwrap_or(constants::DEFAULT_TILE_ROWS);

    println!("📦 Streaming encode of {} → {}", input_path, output_path);

    // In a real streaming producer, these RGBA bytes would arrive
    // incrementally (tile by tile) rather than being fully decoded upfront —
    // see the module doc comment above.
    let img = image::open(input_path)?.to_rgba8();
    let (width, height) = img.dimensions();
    let pixels = img.into_raw();

    let opts = EncoderOptions {
        tile_rows,
        level: 19,
        use_filter: true,
        target_color_type: constants::COLOR_TYPE_RGBA,
        ..Default::default()
    };

    // `File` implements `Write + Seek`, so `finish_exact()` is available:
    // it patches IHDR's `compression_method` byte to its exact value after
    // all tiles are known, instead of the conservative always-ZSTD-bit-set
    // value `Encoder::new()` writes upfront (see `Encoder`'s doc comment
    // for why a plain `Write`-only destination cannot do this).
    let writer = BufWriter::new(File::create(output_path)?);
    let mut encoder = Encoder::new(writer, width, height, &opts)?;

    let row_bytes = (width as usize) * 4;
    let mut tile_count = 0usize;
    let mut y = 0u32;
    while y < height {
        let rows_this_tile = tile_rows.min(height - y);
        let start = (y as usize) * row_bytes;
        let end = start + (rows_this_tile as usize) * row_bytes;
        encoder.add_tile(&pixels[start..end])?;
        tile_count += 1;
        println!(
            "   tile {}: y={}, {} rows submitted",
            tile_count, y, rows_this_tile
        );
        y += rows_this_tile;
    }

    let writer = encoder.finish_exact()?;
    use std::io::Write;
    writer.into_inner()?.flush()?;

    let metadata = std::fs::metadata(output_path)?;
    println!(
        "✅ Success! {} tiles written, {} bytes at {}",
        tile_count,
        metadata.len(),
        output_path
    );

    Ok(())
}
